lines = []
lines.append('@app.post("/audit-maker-checker")')
lines.append('async def audit_maker_checker_endpoint(file: UploadFile = File(...)):')
lines.append('    try:')
lines.append('        content2 = await file.read()')
lines.append('        source, error = safe_read_file(content2, file.filename)')
lines.append('        if error:')
lines.append('            return JSONResponse(status_code=400, content={"filename": file.filename, "error": error})')
lines.append('        result = check_audit_maker_checker(source, file.filename)')
lines.append('        result["filename"] = file.filename')
lines.append('        track_usage("audit-maker-checker", file.filename)')
lines.append('        write_audit_log("audit-maker-checker", file.filename, "checked")')
lines.append('        return result')
lines.append('    except Exception as e:')
lines.append('        return JSONResponse(status_code=400, content={"filename": file.filename, "error": "Audit/Maker-Checker analysis failed safely: " + str(e)})')
lines.append('')

with open("audit_part2_out.txt", "w", encoding="utf-8") as f:
    f.write(chr(10).join(lines))
print("AUDIT-PART2-SAVED")