lines = []
lines.append('def check_audit_maker_checker(source, filename):')
lines.append('    if len(source.encode("utf-8", errors="ignore")) > MAX_FILE_SIZE:')
lines.append('        return {"checked": False, "findings": [], "summary": "File too large."}')
lines.append('    if not filename.lower().endswith(".py"):')
lines.append('        return {"checked": True, "findings": [], "summary": "Audit/Maker-Checker analysis currently supports Python files only."}')
lines.append('    try:')
lines.append('        tree = ast.parse(source)')
lines.append('    except Exception:')
lines.append('        return {"checked": True, "findings": [], "summary": "Could not parse file (non-Python-3 syntax)."}')
lines.append('    _sensitive_name_pattern = re.compile(r"(?i)(transfer|withdraw|deposit|approve|payment|transaction|disburs|refund|debit|credit)")')
lines.append('    _audit_call_pattern = re.compile(r"(?i)(audit|log\\.|logger\\.|logging\\.)")')
lines.append('    _approval_check_pattern = re.compile(r"(?i)(approved|is_approved|authoriz|second.?approv|dual.?control|maker.?check|four.?eyes|4.?eyes)")')
lines.append('    findings = []')
lines.append('    for node in ast.walk(tree):')
lines.append('        if isinstance(node, ast.FunctionDef) and _sensitive_name_pattern.search(node.name):')
lines.append('            func_source = ast.get_source_segment(source, node) or ""')
lines.append('            has_audit_log = bool(_audit_call_pattern.search(func_source))')
lines.append('            has_approval_check = bool(_approval_check_pattern.search(func_source))')
lines.append('            issues = []')
lines.append('            if not has_audit_log:')
lines.append('                issues.append("No audit/logging call detected in this sensitive function.")')
lines.append('            if not has_approval_check and re.search(r"(?i)(approve|disburs|transfer)", node.name):')
lines.append('                issues.append("No maker-checker / dual-approval pattern detected - operation may execute without a second-actor check.")')
lines.append('            if issues:')
lines.append('                findings.append({"function": node.name, "line": node.lineno, "issues": issues})')
lines.append('    return {"checked": True, "findings": findings, "total_findings": len(findings), "summary": str(len(findings)) + " sensitive function(s) flagged.", "disclaimer": "Pattern-based structural check only - looks for logging calls and approval keywords near sensitive function names. Does not verify actual runtime behavior or genuine dual-control enforcement. Manual review against your institution actual control framework required."}')
lines.append('')

with open("audit_part1_out.txt", "w", encoding="utf-8") as f:
    f.write(chr(10).join(lines))
print("AUDIT-PART1-SAVED")