lines = []
lines.append('def check_cnic_validation_quality(source, filename):')
lines.append('    if len(source.encode("utf-8", errors="ignore")) > MAX_FILE_SIZE:')
lines.append('        return {"checked": False, "findings": [], "summary": "File too large."}')
lines.append('    if not filename.lower().endswith(".py"):')
lines.append('        return {"checked": True, "findings": [], "summary": "No CNIC/National ID related code detected."}')
lines.append('    try:')
lines.append('        tree = ast.parse(source)')
lines.append('    except Exception:')
lines.append('        return {"checked": True, "findings": [], "summary": "Could not parse file (non-Python-3 syntax)."}')
lines.append('    _cnic_var_pattern = re.compile(r"(?i)\\b(cnic|national.?id)\\b")')
lines.append('    _strict_length_pattern = re.compile(r"(?i)len\\([^)]*\\)\\s*==\\s*13|len\\([^)]*\\)\\s*!=\\s*13")')
lines.append('    _digit_check_pattern = re.compile(r"(?i)isdigit|isnumeric|\\\\d\\{13\\}|\\\\d\\{5\\}-\\\\d\\{7\\}-\\\\d")')
lines.append('    findings = []')
lines.append('    cnic_functions_found = 0')
lines.append('    for node in ast.walk(tree):')
lines.append('        if isinstance(node, ast.FunctionDef):')
lines.append('            func_source = ast.get_source_segment(source, node) or ""')
lines.append('            _code_only = chr(10).join(l for l in func_source.split(chr(10)) if not l.strip().startswith("#"))')
lines.append('            if not _cnic_var_pattern.search(_code_only):')
lines.append('                continue')
lines.append('            cnic_functions_found += 1')
lines.append('            has_length_check = bool(_strict_length_pattern.search(_code_only))')
lines.append('            has_format_check = bool(_digit_check_pattern.search(_code_only))')
lines.append('            issues = []')
lines.append('            if not has_length_check:')
lines.append('                issues.append("No explicit 13-digit length check found in this CNIC-related function.")')
lines.append('            if not has_format_check:')
lines.append('                issues.append("No explicit numeric/digit-format validation found in this CNIC-related function.")')
lines.append('            if issues:')
lines.append('                findings.append({"function": node.name, "line": node.lineno, "issues": issues})')
lines.append('    if cnic_functions_found == 0:')
lines.append('        return {"checked": True, "findings": [], "summary": "No CNIC/National ID related code detected in this file.", "disclaimer": "Pattern-based function-scope CNIC validation check."}')
lines.append('    return {"checked": True, "findings": findings, "cnic_functions_found": cnic_functions_found, "total_findings": len(findings), "summary": str(len(findings)) + " CNIC validation issue(s) found across " + str(cnic_functions_found) + " function(s).", "disclaimer": "Pattern-based function-scope check for CNIC validation quality - handles aliased/renamed local variables correctly. Does not verify NADRA-level validity."}')
lines.append('')

with open("cnic_p1_out.txt", "w", encoding="utf-8") as f:
    f.write(chr(10).join(lines))
print("CNIC-P1-SAVED")