lines = []
lines.append('def check_ntn_strn_validation_quality(source, filename):')
lines.append('    if len(source.encode("utf-8", errors="ignore")) > MAX_FILE_SIZE:')
lines.append('        return {"checked": False, "findings": [], "summary": "File too large."}')
lines.append('    if not filename.lower().endswith(".py"):')
lines.append('        return {"checked": True, "findings": [], "summary": "No NTN/STRN related code detected."}')
lines.append('    try:')
lines.append('        tree = ast.parse(source)')
lines.append('    except Exception:')
lines.append('        return {"checked": True, "findings": [], "summary": "Could not parse file (non-Python-3 syntax)."}')
lines.append('    _ntn_var_pattern = re.compile(r"(?i)\\b(ntn|strn|tax.?number|tax.?registration)\\b")')
lines.append('    _length_check_pattern = re.compile(r"(?i)len\\([^)]*\\)\\s*[=!]=\\s*\\d+")')
lines.append('    _digit_check_pattern = re.compile(r"(?i)isdigit|isnumeric|\\\\d\\{\\d+\\}")')
lines.append('    findings = []')
lines.append('    ntn_functions_found = 0')
lines.append('    for node in ast.walk(tree):')
lines.append('        if isinstance(node, ast.FunctionDef):')
lines.append('            func_source = ast.get_source_segment(source, node) or ""')
lines.append('            _code_only = chr(10).join(l for l in func_source.split(chr(10)) if not l.strip().startswith("#"))')
lines.append('            if not _ntn_var_pattern.search(_code_only):')
lines.append('                continue')
lines.append('            ntn_functions_found += 1')
lines.append('            has_length_check = bool(_length_check_pattern.search(_code_only))')
lines.append('            has_format_check = bool(_digit_check_pattern.search(_code_only))')
lines.append('            issues = []')
lines.append('            if not has_length_check:')
lines.append('                issues.append("No explicit length check found in this NTN/STRN-related function.")')
lines.append('            if not has_format_check:')
lines.append('                issues.append("No explicit numeric/digit-format validation found in this NTN/STRN-related function.")')
lines.append('            if issues:')
lines.append('                findings.append({"function": node.name, "line": node.lineno, "issues": issues})')
lines.append('    if ntn_functions_found == 0:')
lines.append('        return {"checked": True, "findings": [], "summary": "No NTN/STRN related code detected in this file.", "disclaimer": "Pattern-based function-scope NTN/STRN validation check."}')
lines.append('    return {"checked": True, "findings": findings, "ntn_functions_found": ntn_functions_found, "total_findings": len(findings), "summary": str(len(findings)) + " NTN/STRN validation issue(s) found across " + str(ntn_functions_found) + " function(s).", "disclaimer": "Pattern-based function-scope check - handles aliased/renamed local variables correctly. Does not assert specific correct digit count - consult current FBR guidance. Does not verify FBR-level validity."}')
lines.append('')

with open("ntn_p1_out.txt", "w", encoding="utf-8") as f:
    f.write(chr(10).join(lines))
print("NTN-P1-SAVED")