with open("main.py", "r", encoding="utf-8") as f:
    lines = f.readlines()

start_idx = 265
end_idx = 285

print("Line at start (266):", repr(lines[265]))
print("Line at end (285):", repr(lines[284]))

new_block = []
new_block.append("def _ast_complexity_python(source):\n")
new_block.append("    try:\n")
new_block.append("        tree = ast.parse(source)\n")
new_block.append("    except Exception:\n")
new_block.append("        return None\n")
new_block.append("    func_scores = []\n")
new_block.append("    for node in ast.walk(tree):\n")
new_block.append("        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):\n")
new_block.append("            complexity = 1\n")
new_block.append("            for child in ast.walk(node):\n")
new_block.append("                if isinstance(child, (ast.If, ast.For, ast.AsyncFor, ast.While, ast.ExceptHandler, ast.With, ast.AsyncWith)):\n")
new_block.append("                    complexity += 1\n")
new_block.append("                elif isinstance(child, ast.BoolOp):\n")
new_block.append("                    complexity += max(0, len(child.values) - 1)\n")
new_block.append("                elif isinstance(child, ast.IfExp):\n")
new_block.append("                    complexity += 1\n")
new_block.append("                elif isinstance(child, (ast.comprehension,)):\n")
new_block.append("                    complexity += len(child.ifs)\n")
new_block.append("            func_scores.append(complexity)\n")
new_block.append("    if not func_scores:\n")
new_block.append("        return None\n")
new_block.append("    avg_score = round(sum(func_scores) / len(func_scores), 1)\n")
new_block.append("    max_score = max(func_scores)\n")
new_block.append("    return {\"avg\": avg_score, \"max\": max_score, \"func_count\": len(func_scores)}\n")
new_block.append("\n")
new_block.append("def calculate_complexity(source):\n")
new_block.append("    ast_result = _ast_complexity_python(source)\n")
new_block.append("    if ast_result is not None:\n")
new_block.append("        score = ast_result[\"avg\"]\n")
new_block.append("        method = \"ast\"\n")
new_block.append("        func_count = ast_result[\"func_count\"]\n")
new_block.append("        extra = {\"max_function_complexity\": ast_result[\"max\"], \"method\": \"ast (McCabe cyclomatic complexity, averaged per function)\"}\n")
new_block.append("    else:\n")
new_block.append('        keywords = ["if ", "elif ", "for ", "while ", "except", " and ", " or ", "case "]\n')
new_block.append("        raw_score = 1\n")
new_block.append("        for kw in keywords:\n")
new_block.append("            raw_score += source.count(kw)\n")
new_block.append('        func_patterns = [r"\\bdef\\s+\\w+\\s*\\(", r"\\bfunction\\s+\\w+\\s*\\(", r"(?:public|private|protected)\\s+(?:static\\s+)?[\\w<>\\[\\]]+\\s+\\w+\\s*\\("]\n')
new_block.append("        func_count = 0\n")
new_block.append("        for fp in func_patterns:\n")
new_block.append("            func_count += len(re.findall(fp, source))\n")
new_block.append("        func_count = max(1, func_count)\n")
new_block.append("        score = round(raw_score / func_count, 1) if func_count > 1 else raw_score\n")
new_block.append("        method = \"keyword-heuristic\"\n")
new_block.append("        extra = {\"method\": \"keyword-based heuristic (approximate - full parser not available for this language)\"}\n")
new_block.append("    if score <= 5:\n")
new_block.append('        level = "Low complexity"\n')
new_block.append("    elif score <= 10:\n")
new_block.append('        level = "Moderate complexity"\n')
new_block.append("    elif score <= 20:\n")
new_block.append('        level = "High complexity"\n')
new_block.append("    else:\n")
new_block.append('        level = "Very high complexity"\n')
new_block.append('    result = {"complexity_score": score, "complexity_level": level, "estimated_functions": func_count}\n')
new_block.append("    result.update(extra)\n")
new_block.append("    return result\n")
new_block.append("\n")

lines[start_idx:end_idx] = new_block

with open("main.py", "w", encoding="utf-8") as f:
    f.writelines(lines)

print("PATCHED SUCCESSFULLY")