lines = []
lines.append('def check_structuring_patterns(source, filename):')
lines.append('    if len(source.encode("utf-8", errors="ignore")) > MAX_FILE_SIZE:')
lines.append('        return {"checked": False, "findings": [], "summary": "File too large."}')
lines.append('    if not filename.lower().endswith(".py"):')
lines.append('        return {"checked": True, "findings": [], "summary": "Structuring pattern analysis currently supports Python files only."}')
lines.append('    try:')
lines.append('        tree = ast.parse(source)')
lines.append('    except Exception:')
lines.append('        return {"checked": True, "findings": [], "summary": "Could not parse file (non-Python-3 syntax)."}')
lines.append('    _txn_name_pattern = re.compile(r"(?i)(transfer|withdraw|deposit|payment|transaction|disburs)")')
lines.append('    _velocity_pattern = re.compile(r"(?i)(daily.?limit|daily.?total|cumulative|aggregate|velocity|total.?today|running.?total|sum.?today)")')
lines.append('    _suspicious_split_pattern = re.compile(r"(?i)(split.?transaction|structur|smurf|avoid.?report|below.?threshold|under.?limit)")')
lines.append('    findings = []')
lines.append('    for node in ast.walk(tree):')
lines.append('        if isinstance(node, ast.FunctionDef) and _txn_name_pattern.search(node.name):')
lines.append('            func_source = ast.get_source_segment(source, node) or ""')
lines.append('            _code_only_lines = [l for l in func_source.split(chr(10)) if not l.strip().startswith("#")]')
lines.append('            _code_only = chr(10).join(_code_only_lines)')
lines.append('            has_velocity_check = bool(_velocity_pattern.search(_code_only))')
lines.append('            has_suspicious_hint = bool(_suspicious_split_pattern.search(func_source))')
lines.append('            issues = []')
lines.append('            if not has_velocity_check:')
lines.append('                issues.append("No cumulative/velocity tracking detected - this function may evaluate each transaction in isolation, exploitable by structuring/smurfing.")')
lines.append('            if has_suspicious_hint:')
lines.append('                issues.append("Comment or identifier suggests transaction-splitting or threshold-avoidance logic - flag for manual compliance review.")')
lines.append('            if issues:')
lines.append('                findings.append({"function": node.name, "line": node.lineno, "issues": issues})')
lines.append('    return {"checked": True, "findings": findings, "total_findings": len(findings), "summary": str(len(findings)) + " transaction function(s) flagged.", "disclaimer": "Pattern-based structural check only. Does NOT perform actual AML structuring detection (requires transaction-history analysis, not static code review), does not verify real threshold values, cannot determine intent. A qualified AML compliance officer must review flagged functions."}')
lines.append('')

with open("struct_part1_out.txt", "w", encoding="utf-8") as f:
    f.write(chr(10).join(lines))
print("STRUCT-PART1-SAVED")